drop table if exists public.proyek cascade;

create table public.proyek (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null check (kategori in ('Web', 'Mobile', 'Design')),
  deskripsi_singkat text not null,
  deskripsi_lengkap text not null,
  teknologi text[] not null default '{}',
  tautan text,
  label_tautan text,
  created_at timestamptz not null default now()
);

alter table public.proyek enable row level security;

create policy "Public can read projects"
on public.proyek
for select
to anon, authenticated
using (true);

insert into public.proyek (
  judul,
  kategori,
  deskripsi_singkat,
  deskripsi_lengkap,
  teknologi,
  tautan,
  label_tautan
)
values
  (
    'Manajemen Siswa',
    'Web',
    'Website untuk mengelola dan menampilkan data siswa secara lebih terstruktur.',
    'Project ini membantu menyusun dan menampilkan data siswa secara terstruktur agar informasi lebih mudah dikelola dan dibaca.',
    array['Next.js', 'TypeScript', 'CSS'],
    null,
    null
  ),
  (
    'Manajemen Magang',
    'Web',
    'Sistem untuk membantu pengelolaan data dan kegiatan siswa selama proses magang.',
    'Project ini dirancang untuk membantu pencatatan data serta kegiatan siswa selama menjalani program magang.',
    array['Next.js', 'React', 'CSS'],
    null,
    null
  ),
  (
    'NextJS V2',
    'Web',
    'Project website menggunakan Next.js sebagai pengembangan dari project sebelumnya.',
    'NextJS V2 adalah pengembangan lanjutan untuk mempraktikkan routing, layout, dan struktur aplikasi Next.js yang lebih rapi.',
    array['Next.js', 'TypeScript', 'App Router'],
    null,
    null
  ),
  (
    'My App',
    'Web',
    'Project aplikasi yang dikerjakan sebagai bagian dari pembelajaran web development.',
    'Aplikasi ini menjadi latihan untuk menerapkan konsep antarmuka dan alur aplikasi web dalam project yang bisa dibuka secara online.',
    array['Web Application', 'Next.js'],
    'https://myapp-reyhan-purnomo-putra1-c1larj6je-rr-7229.vercel.app/',
    'Open My App'
  ),
  (
    'Mobile UI Design',
    'Design',
    'Desain interface aplikasi mobile yang dibuat menggunakan Figma.',
    'Project ini berisi rancangan interface mobile dengan fokus pada susunan layar, navigasi, dan pengalaman pengguna.',
    array['Figma', 'Mobile UI'],
    'https://swore-raven-74257261.figma.site/#/mobile',
    'View Mobile Design'
  ),
  (
    'Web UI Design',
    'Design',
    'Desain interface website dengan memperhatikan struktur dan tampilan pengguna.',
    'Project ini mengeksplorasi rancangan interface website yang terstruktur, mudah dipahami, dan nyaman digunakan.',
    array['Figma', 'Web UI'],
    'https://swore-raven-74257261.figma.site/#/web',
    'View Web Design'
  );