create table if not exists public.proyek (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null check (kategori in ('Web', 'Mobile', 'Design')),
  deskripsi_singkat text not null,
  deskripsi_lengkap text not null,
  teknologi text[] not null default '{}',
  tautan text,
  label_tautan text,
  created_at timestamptz not null default now()
);

alter table public.proyek enable row level security;

create policy "Public can read projects"
on public.proyek
for select
to anon, authenticated
using (true);